"""WES SNV Phase 1 end-to-end: Mutect2 → upstream (pVAC) → score."""

from __future__ import annotations

import datetime
import textwrap
from pathlib import Path

from ..pipeline import run
from ..tools.upstream import run_upstream
from .mutect2 import run_filter_mutect_calls, run_mutect2_paired


def write_snv_run_config(
    *,
    path: str | Path,
    sample_id: str,
    profile: str,
    tumor_vcf: str | Path,
    hla_alleles: list[str],
    tumor_sample_name: str,
    normal_sample_name: str | None = None,
    stub: bool = True,
    expression: str | Path | None = None,
    cnv: str | Path | None = None,
    normal_expression: str | Path | None = None,
    normal_hla_ligands: str | Path | None = None,
    pass_only: bool = True,
) -> Path:
    """Write a run TOML for neoag run-upstream after Mutect2."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    vcf = Path(tumor_vcf).resolve()
    hla_lines = ",\n".join(f'  "{a}"' for a in hla_alleles)
    enabled = '["pvacseq", "netmhcpan", "mhcflurry", "vep"]'
    expr = f'expression = "{expression}"' if expression else 'expression = "data/fixtures/gene_expression.tsv"'
    cnv_line = f'cnv = "{cnv}"' if cnv else 'cnv = "data/fixtures/cnv_segments.tsv"'
    nexpr = (
        f'normal_expression = "{normal_expression}"'
        if normal_expression
        else 'normal_expression = "resources/normal_expression.example.tsv"'
    )
    nlig = (
        f'normal_hla_ligands = "{normal_hla_ligands}"'
        if normal_hla_ligands
        else 'normal_hla_ligands = "resources/normal_hla_ligands.example.tsv"'
    )
    normal_line = f'normal_sample_name = "{normal_sample_name}"' if normal_sample_name else ""
    pass_only_line = "pass_only = false" if not pass_only else ""
    pvacseq_enrich_line = "pvacseq_enrich = false" if stub else "# pvacseq_enrich = true"
    body = textwrap.dedent(
        f"""\
        # Auto-generated by neoag snv-run-full-wes ({datetime.datetime.now(datetime.UTC).isoformat()}Z)

        [sample]
        id = "{sample_id}"
        profile = "{profile}"
        outdir = "results/{sample_id}_snv_wes"

        [tools]
        stub = {"true" if stub else "false"}
        enabled = {enabled}

        [inputs]
        hla_alleles = [
        {hla_lines}
        ]
        tumor_vcf = "{vcf}"
        tumor_sample_name = "{tumor_sample_name}"
        {normal_line}
        {pass_only_line}
        variants_vcf = "{vcf}"
        extract_appm_from_vcf = true
        {pvacseq_enrich_line}
        {expr}
        {cnv_line}
        {nexpr}
        {nlig}
        """
    ).strip() + "\n"
    path.write_text(body, encoding="utf-8")
    return path


def run_snv_wes_call(
    *,
    outdir: str | Path,
    tumor_bam: str | Path,
    normal_bam: str | Path,
    reference_fasta: str | Path,
    intervals_bed: str | Path,
    tumor_sample_name: str,
    normal_sample_name: str,
    sample_id: str,
    gatk: str | None = None,
    germline_resource: str | Path | None = None,
    panel_of_normals: str | Path | None = None,
) -> dict[str, str]:
    """Mutect2 paired + FilterMutectCalls for WES."""
    outdir = Path(outdir)
    calling = outdir / "calling"
    calling.mkdir(parents=True, exist_ok=True)
    raw_vcf = calling / f"{sample_id}.mutect2.raw.vcf.gz"
    filtered_vcf = calling / f"{sample_id}.mutect2.filtered.vcf.gz"

    run_mutect2_paired(
        tumor_bam=tumor_bam,
        normal_bam=normal_bam,
        reference_fasta=reference_fasta,
        intervals_bed=intervals_bed,
        tumor_sample_name=tumor_sample_name,
        normal_sample_name=normal_sample_name,
        out_vcf=raw_vcf,
        workdir=calling / "mutect2",
        gatk=gatk,
    )
    run_filter_mutect_calls(
        reference_fasta=reference_fasta,
        unfiltered_vcf=raw_vcf,
        out_vcf=filtered_vcf,
        workdir=calling / "filter",
        gatk=gatk,
        germline_resource=germline_resource,
        panel_of_normals=panel_of_normals,
    )
    return {
        "mutect2_raw_vcf": str(raw_vcf),
        "mutect2_filtered_vcf": str(filtered_vcf),
    }


def run_snv_wes_full(
    *,
    outdir: str | Path,
    sample_id: str,
    profile: str,
    hla_alleles: list[str],
    tumor_sample_name: str,
    normal_sample_name: str | None = None,
    somatic_vcf: str | Path | None = None,
    tumor_bam: str | Path | None = None,
    normal_bam: str | Path | None = None,
    reference_fasta: str | Path | None = None,
    intervals_bed: str | Path | None = None,
    upstream_stub: bool = True,
    immunogenicity_stub: bool = False,
    gatk: str | None = None,
    germline_resource: str | Path | None = None,
    panel_of_normals: str | Path | None = None,
    expression: str | Path | None = None,
    cnv: str | Path | None = None,
    normal_expression: str | Path | None = None,
    normal_hla_ligands: str | Path | None = None,
    tool_executables: dict | None = None,
    pass_only: bool = True,
) -> dict[str, str]:
    """Mutect2 (optional) → pVAC upstream → score."""
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    if somatic_vcf:
        filtered_vcf = Path(somatic_vcf)
        if not filtered_vcf.is_file():
            raise FileNotFoundError(f"somatic_vcf not found: {filtered_vcf}")
        call_out = {"mutect2_filtered_vcf": str(filtered_vcf)}
    else:
        if not all([tumor_bam, normal_bam, reference_fasta, intervals_bed, normal_sample_name]):
            raise ValueError(
                "Provide --somatic-vcf or all of: tumor/normal BAM, reference, intervals, normal sample name"
            )
        call_out = run_snv_wes_call(
            outdir=outdir,
            tumor_bam=tumor_bam,
            normal_bam=normal_bam,
            reference_fasta=reference_fasta,
            intervals_bed=intervals_bed,
            tumor_sample_name=tumor_sample_name,
            normal_sample_name=normal_sample_name,
            sample_id=sample_id,
            gatk=gatk,
            germline_resource=germline_resource,
            panel_of_normals=panel_of_normals,
        )
        filtered_vcf = Path(call_out["mutect2_filtered_vcf"])

    cfg_path = outdir / "run.snv_wes.generated.toml"
    write_snv_run_config(
        path=cfg_path,
        sample_id=sample_id,
        profile=profile,
        tumor_vcf=filtered_vcf,
        hla_alleles=hla_alleles,
        tumor_sample_name=tumor_sample_name,
        normal_sample_name=normal_sample_name,
        stub=upstream_stub,
        expression=expression,
        cnv=cnv,
        normal_expression=normal_expression,
        normal_hla_ligands=normal_hla_ligands,
        pass_only=pass_only,
    )
    upstream = run_upstream(cfg_path, outdir / "upstream")

    pvac = []
    for key in ("pvacseq", "pvacfuse"):
        if key in upstream:
            pvac.append(upstream[key])
    if not pvac:
        from ..tools.registry import ROOT

        pvac = [
            str(ROOT / "data" / "fixtures" / "pvacseq_aggregated.tsv"),
            str(ROOT / "data" / "fixtures" / "pvacfuse_aggregated.tsv"),
        ]

    score_out = run(
        outdir=outdir,
        profile_name_or_path=profile,
        sample_id=sample_id,
        pvac_paths=pvac,
        netmhcpan=upstream.get("netmhcpan"),
        mhcflurry=upstream.get("mhcflurry"),
        netmhcstabpan=upstream.get("netmhcstabpan"),
        vep_appm=upstream.get("vep_appm"),
        expression=upstream.get("expression"),
        hla_loh=upstream.get("hla_loh"),
        purity=upstream.get("purity"),
        cnv=upstream.get("cnv"),
        normal_expression=upstream.get("normal_expression"),
        normal_hla_ligands=upstream.get("normal_hla_ligands"),
        immunogenicity_stub=immunogenicity_stub,
        tool_executables=tool_executables or {},
    )
    return {**call_out, "run_config": str(cfg_path), **score_out}
