#!/usr/bin/env bash
# Plan A setup on destination server after rsync or tar extract.
#
# Usage (on na@10.200.50.134):
#   cd /home/na/project/neoag_event_pipeline_v03_rc
#   bash scripts/migrate_setup_plan_a.sh
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONDA_BASE="${CONDA_BASE:-$(conda info --base 2>/dev/null || echo "${HOME}/miniconda3")}"
PROJECT="${NEOAG_TOOLS_ROOT:-${ROOT}}"

echo "==> Plan A setup"
echo "    PROJECT=${PROJECT}"
echo "    CONDA_BASE=${CONDA_BASE}"

if ! command -v conda >/dev/null 2>&1; then
  echo "ERROR: conda not found. Install Miniconda first:" >&2
  echo "  wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh" >&2
  echo "  bash Miniconda3-latest-Linux-x86_64.sh -b -p ${CONDA_BASE}" >&2
  exit 1
fi

# shellcheck disable=SC1091
source "${CONDA_BASE}/etc/profile.d/conda.sh"

unpack_pack() {
  local env="$1"
  local tgz="${PROJECT}/conda_packs/${env}.tar.gz"
  local dest="${CONDA_BASE}/envs/${env}"
  if [[ ! -f "${tgz}" ]]; then
    echo "    skip unpack ${env} (no ${tgz})"
    return 0
  fi
  echo "==> Unpacking ${env} from conda_packs ..."
  mkdir -p "${dest}"
  tar -xzf "${tgz}" -C "${dest}"
  if [[ -x "${dest}/bin/conda-unpack" ]]; then
    "${dest}/bin/conda-unpack"
  fi
}

for env in neoag-vep neoag-gatk neoag-sv neoag-manta; do
  unpack_pack "${env}"
done

echo "==> Creating neoag-tools (cannot conda-pack editable installs) ..."
NEOAG_TOOLS_LITE=1 bash "${PROJECT}/scripts/setup_tools_env.sh"

echo "==> Python package + venv ..."
python3 -m venv "${PROJECT}/.venv"
# shellcheck disable=SC1091
source "${PROJECT}/.venv/bin/activate"
pip install -q -U pip
pip install -q -e "${PROJECT}/.[test]"

echo "==> Writing conf/tools.env.sh for this host ..."
cat > "${PROJECT}/conf/tools.env.sh" <<EOF
# Generated by scripts/migrate_setup_plan_a.sh
export NEOAG_CONDA_ENV="neoag-tools"
export NEOAG_TOOLS_ROOT="${PROJECT}"
export PATH="${CONDA_BASE}/envs/neoag-tools/bin:\${PATH}"
export LD_LIBRARY_PATH="${CONDA_BASE}/envs/neoag-tools/lib:\${LD_LIBRARY_PATH:-}"
export TF_USE_LEGACY_KERAS=1
export NEOAG_VEP_ENV="neoag-vep"
export NEOAG_VEP_BIN="\${NEOAG_TOOLS_ROOT}/bin/vep-neoag"
export DEEPIMMUNO_DIR="\${NEOAG_TOOLS_ROOT}/tools/DeepImmuno"
export BIGMHC_DIR="\${NEOAG_TOOLS_ROOT}/tools/bigmhc"
export PRIME_HOME="\${NEOAG_TOOLS_ROOT}/tools/prime"
export NEOAG_PRIME_BIN="\${PRIME_HOME}/PRIME"
export MIXMHCPRED_HOME="\${NEOAG_TOOLS_ROOT}/tools/mixMHCpred_install"
export MIXMHCPRED_BIN="\${MIXMHCPRED_HOME}/MixMHCpred"
export PATH="\${PRIME_HOME}:\${MIXMHCPRED_HOME}:\${PATH}"
export NETMHCPAN_HOME="\${NEOAG_TOOLS_ROOT}/tools/netMHCpan"
if [[ -x "\${NETMHCPAN_HOME}/netMHCpan" ]]; then
  export PATH="\${NETMHCPAN_HOME}:\${PATH}"
fi
export NETMHCSTABPAN_HOME="\${NEOAG_TOOLS_ROOT}/tools/netMHCstabpan"
if [[ -x "\${NETMHCSTABPAN_HOME}/netMHCstabpan" ]]; then
  export PATH="\${NETMHCSTABPAN_HOME}:\${PATH}"
fi
export LOHHLA_HOME="\${NEOAG_TOOLS_ROOT}/tools/lohhla"
export FACETS_HOME="\${NEOAG_TOOLS_ROOT}/tools/facets"
export NEOAG_SV_ENV="neoag-sv"
export NEOAG_MANTA_ENV="neoag-manta"
export PATH="\${NEOAG_TOOLS_ROOT}/bin:\${LOHHLA_HOME}:\${FACETS_HOME}:\${PATH}"
if [[ -d "${CONDA_BASE}/envs/\${NEOAG_SV_ENV}/bin" ]]; then
  export PATH="${CONDA_BASE}/envs/\${NEOAG_SV_ENV}/bin:\${PATH}"
fi
if [[ -d "${CONDA_BASE}/envs/\${NEOAG_MANTA_ENV}/bin" ]]; then
  export PATH="${CONDA_BASE}/envs/\${NEOAG_MANTA_ENV}/bin:\${PATH}"
fi
export NEOAG_GATK_ENV="neoag-gatk"
if [[ -d "${CONDA_BASE}/envs/\${NEOAG_GATK_ENV}/bin" ]]; then
  export PATH="${CONDA_BASE}/envs/\${NEOAG_GATK_ENV}/bin:\${PATH}"
fi
export NEOAG_FUSION_ENV="neoag-fusion"
export NEOAG_STAR_FUSION_HOME="\${NEOAG_TOOLS_ROOT}/tools/STAR-Fusion"
export NEOAG_FUSIONCATCHER_HOME="\${NEOAG_TOOLS_ROOT}/tools/fusioncatcher"
export NEOAG_EASYFUSE_HOME="\${NEOAG_TOOLS_ROOT}/tools/EasyFuse"
if [[ -d "${CONDA_BASE}/envs/\${NEOAG_FUSION_ENV}/bin" ]]; then
  export PATH="${CONDA_BASE}/envs/\${NEOAG_FUSION_ENV}/bin:\${PATH}"
fi
if [[ -d "\${NEOAG_STAR_FUSION_HOME}" ]]; then
  export PATH="\${NEOAG_STAR_FUSION_HOME}:\${PATH}"
fi
EOF

echo "==> Optional: fusion tools (if not yet installed) ..."
bash "${PROJECT}/scripts/install_fusion_tools.sh" || echo "WARN: fusion install incomplete"

echo "==> Verify ..."
# shellcheck disable=SC1091
source "${PROJECT}/conf/tools.env.sh"
export PATH="${PROJECT}/.venv/bin:${PATH}"
neoag-v03 check-tools || true
pytest -q "${PROJECT}/tests" || true

echo ""
echo "==> Setup done."
echo "    source ${PROJECT}/conf/tools.env.sh"
echo "    source ${PROJECT}/.venv/bin/activate"
