#!/usr/bin/env bash
# Run pVACbind from a Splice Provenance Layer FASTA and emit an auditable output list.
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  bash scripts/run_pvacbind_sample.sh \
    --fasta splice_pvacbind_input.fasta \
    --sample-id SAMPLE001 \
    --hla HLA-A*02:01,HLA-B*07:02 \
    --algorithms MHCflurry,MHCflurryEL \
    --outdir results/pvacbind [options]

Required:
  --fasta PATH                 FASTA generated by neoag-splice-layer
  --sample-id ID               Sample name used by pVACbind
  --hla LIST | --hla-file PATH Comma/newline-separated HLA alleles
  --outdir DIR                 pVACbind output directory

Options:
  --algorithms LIST            Comma-separated algorithms (default: MHCflurry)
  --threads N                  Prediction threads (default: 4)
  --class-i-lengths LIST       Default: 8,9,10,11
  --class-ii-lengths LIST      Default: 12,13,14,15,16,17,18
  --iedb-install-directory DIR Local IEDB installation
  --reference-proteome FASTA   Enable pVACbind reference-proteome similarity
  --extra-arg ARG              Repeatable raw pVACbind option; reviewed use only
  --pvacbind-bin PATH          Override pvacbind executable

Outputs:
  OUTDIR/pvacbind_all_epitopes.list
  OUTDIR/pvacbind_run_manifest.json
USAGE
}

FASTA=""; SAMPLE_ID=""; HLA=""; HLA_FILE=""; OUTDIR=""
ALGORITHMS="${NEOAG_PVACBIND_ALGORITHMS:-MHCflurry}"
THREADS="${NEOAG_PVACBIND_THREADS:-4}"
CLASS_I_LENGTHS="${NEOAG_PVACBIND_CLASS_I_LENGTHS:-8,9,10,11}"
CLASS_II_LENGTHS="${NEOAG_PVACBIND_CLASS_II_LENGTHS:-12,13,14,15,16,17,18}"
IEDB_DIR=""; REFERENCE_PROTEOME=""; PVACBIND_BIN="${NEOAG_PVACBIND_BIN:-}"
EXTRA_ARGS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --fasta) FASTA="$2"; shift 2 ;;
    --sample-id) SAMPLE_ID="$2"; shift 2 ;;
    --hla) HLA="$2"; shift 2 ;;
    --hla-file) HLA_FILE="$2"; shift 2 ;;
    --outdir) OUTDIR="$2"; shift 2 ;;
    --algorithms) ALGORITHMS="$2"; shift 2 ;;
    --threads) THREADS="$2"; shift 2 ;;
    --class-i-lengths) CLASS_I_LENGTHS="$2"; shift 2 ;;
    --class-ii-lengths) CLASS_II_LENGTHS="$2"; shift 2 ;;
    --iedb-install-directory) IEDB_DIR="$2"; shift 2 ;;
    --reference-proteome) REFERENCE_PROTEOME="$2"; shift 2 ;;
    --extra-arg) EXTRA_ARGS+=("$2"); shift 2 ;;
    --pvacbind-bin) PVACBIND_BIN="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "ERROR: unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

[[ -n "$FASTA" && -s "$FASTA" ]] || { echo "ERROR: --fasta is missing or empty: $FASTA" >&2; exit 2; }
[[ -n "$SAMPLE_ID" ]] || { echo "ERROR: --sample-id is required" >&2; exit 2; }
[[ -n "$OUTDIR" ]] || { echo "ERROR: --outdir is required" >&2; exit 2; }
if [[ -n "$HLA_FILE" ]]; then
  [[ -s "$HLA_FILE" ]] || { echo "ERROR: --hla-file is missing or empty: $HLA_FILE" >&2; exit 2; }
  HLA="$(python - "$HLA_FILE" <<'PY'
from pathlib import Path
import re, sys
text = Path(sys.argv[1]).read_text(encoding='utf-8')
values = [x.strip() for x in re.split(r'[,;\s]+', text) if x.strip() and not x.lstrip().startswith('#')]
print(','.join(dict.fromkeys(values)))
PY
)"
fi
[[ -n "$HLA" ]] || { echo "ERROR: --hla or --hla-file is required" >&2; exit 2; }
[[ "$THREADS" =~ ^[1-9][0-9]*$ ]] || { echo "ERROR: --threads must be a positive integer" >&2; exit 2; }
if [[ -n "$REFERENCE_PROTEOME" ]]; then
  [[ -s "$REFERENCE_PROTEOME" ]] || { echo "ERROR: reference proteome missing: $REFERENCE_PROTEOME" >&2; exit 2; }
fi
if [[ -z "$PVACBIND_BIN" ]]; then
  PVACBIND_BIN="$(command -v pvacbind-neoag || command -v pvacbind || true)"
fi
[[ -n "$PVACBIND_BIN" && -x "$PVACBIND_BIN" ]] || { echo "ERROR: pvacbind executable not found" >&2; exit 3; }

IFS=',' read -r -a ALGORITHM_ARGS <<< "$ALGORITHMS"
[[ ${#ALGORITHM_ARGS[@]} -gt 0 ]] || { echo "ERROR: --algorithms resolved to an empty list" >&2; exit 2; }
mkdir -p "$OUTDIR"

args=(run "$FASTA" "$SAMPLE_ID" "$HLA")
for algorithm in "${ALGORITHM_ARGS[@]}"; do
  algorithm="${algorithm//[[:space:]]/}"
  [[ -n "$algorithm" ]] && args+=("$algorithm")
done
args+=("$OUTDIR" -t "$THREADS" -e1 "$CLASS_I_LENGTHS" -e2 "$CLASS_II_LENGTHS")
[[ -n "$IEDB_DIR" ]] && args+=(--iedb-install-directory "$IEDB_DIR")
if [[ -n "$REFERENCE_PROTEOME" ]]; then
  args+=(--run-reference-proteome-similarity --peptide-fasta "$REFERENCE_PROTEOME")
fi
args+=("${EXTRA_ARGS[@]}")

"$PVACBIND_BIN" "${args[@]}"

LIST="$OUTDIR/pvacbind_all_epitopes.list"
find "$OUTDIR" -type f -name '*.all_epitopes.tsv' ! -name '*.aggregated.tsv' -print | LC_ALL=C sort > "$LIST"
[[ -s "$LIST" ]] || { echo "ERROR: pVACbind completed but no *.all_epitopes.tsv was found" >&2; exit 4; }

python - "$FASTA" "$SAMPLE_ID" "$HLA" "$ALGORITHMS" "$OUTDIR" "$PVACBIND_BIN" "$LIST" <<'PY'
from __future__ import annotations
import hashlib, json, subprocess, sys
from datetime import datetime, timezone
from pathlib import Path

fasta, sample, hla, algorithms, outdir, executable, list_path = sys.argv[1:]
def sha(path: Path) -> str:
    h = hashlib.sha256()
    with path.open('rb') as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b''):
            h.update(chunk)
    return h.hexdigest()
try:
    version = subprocess.run([executable, '--version'], text=True, capture_output=True, check=False).stdout.strip()
except OSError:
    version = 'UNASSESSED'
files = [Path(line.strip()) for line in Path(list_path).read_text().splitlines() if line.strip()]
payload = {
    'schema_version': 'neoag-pvacbind-run-v1',
    'created_at': datetime.now(timezone.utc).isoformat(),
    'sample_id': sample,
    'hla_alleles': hla.split(','),
    'algorithms': [x for x in algorithms.split(',') if x],
    'executable': executable,
    'version': version or 'UNASSESSED',
    'input_fasta': {'path': str(Path(fasta).resolve()), 'sha256': sha(Path(fasta))},
    'all_epitopes': [{'path': str(path.resolve()), 'sha256': sha(path)} for path in files],
}
Path(outdir, 'pvacbind_run_manifest.json').write_text(json.dumps(payload, indent=2) + '\n', encoding='utf-8')
PY

printf '%s\n' "$LIST"
