#!/usr/bin/env bash
# Create conda env neoag-tools (pVACtools, MHCflurry, VEP) and write activation helpers.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_NAME="${NEOAG_CONDA_ENV:-neoag-tools}"
# Use NEOAG_TOOLS_LITE=1 to skip heavy conda pytorch/cuda stack for MHCflurry
if [[ "${NEOAG_TOOLS_LITE:-0}" == "1" ]]; then
  YML="${ROOT}/conda/env.neoag-tools-lite.yml"
else
  YML="${ROOT}/conda/env.neoag-tools.yml"
fi
TOOLS_ENV_SH="${ROOT}/conf/tools.env.sh"
NETMHCPAN_HOME="${NEOAG_NETMHCPAN_HOME:-${NETMHCPAN_HOME:-${ROOT}/tools/netMHCpan}}"

echo "==> Project: ${ROOT}"
echo "==> Conda env: ${ENV_NAME}"

if [[ -n "${NEOAG_CONDA_BASE:-}" ]]; then
  export PATH="${NEOAG_CONDA_BASE}/bin:${PATH}"
fi
if ! command -v conda >/dev/null 2>&1; then
  echo "ERROR: conda not found. Install Miniconda/Mambaforge first." >&2
  exit 1
fi

CONDA_BASE="${NEOAG_CONDA_BASE:-$(command conda info --base)}"
CONDA_BIN="${CONDA_BASE}/bin/conda"
if [[ ! -x "${CONDA_BIN}" ]]; then
  echo "ERROR: conda executable not found at ${CONDA_BIN}" >&2
  exit 1
fi

# Some conda activation/deactivation hooks reference unset CONDA_BACKUP_*
# variables. Keep nounset off only while calling conda shell machinery.
conda_safe() {
  set +u
  "${CONDA_BIN}" "$@"
  local rc=$?
  set -u
  return "$rc"
}

# shellcheck disable=SC1091
set +u
source "${CONDA_BASE}/etc/profile.d/conda.sh"
set -u

if conda_safe env list | awk '{print $1}' | grep -qx "${ENV_NAME}"; then
  echo "==> Env '${ENV_NAME}' exists; updating..."
  conda_safe env update -n "${ENV_NAME}" -f "${YML}" --prune
else
  echo "==> Creating env from ${YML} (may take 10–30 min)..."
  conda_safe env create -n "${ENV_NAME}" -f "${YML}"
fi

set +u
conda activate "${ENV_NAME}"
set -u
# Prefer conda C++ runtime during smoke tests; avoids system libstdc++/CXXABI mismatches.
export LD_LIBRARY_PATH="${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH:-}"

echo "==> Verifying pVACtools (pip) ..."
if ! command -v pvacseq >/dev/null 2>&1; then
  echo "==> Installing pvactools via pip ..."
  pip install "pvactools>=6.1,<7"
fi

echo "==> Ensuring setuptools<82 (pkg_resources required by mhcflurry) ..."
pip install -q "setuptools>=65,<82"

echo "==> Ensuring Biopython ..."
pip install -q biopython

echo "==> Ensuring tf-keras legacy shim for MHCflurry ..."
TF_KERAS_SPEC="$(python - <<'PY'
import tensorflow as tf
major, minor, *_ = tf.__version__.split(".")
print(f"tf-keras>={major}.{minor},<{major}.{int(minor) + 1}")
PY
)"
pip install -q "${TF_KERAS_SPEC}"

echo "==> Fetching MHCflurry models..."
if command -v mhcflurry-downloads >/dev/null 2>&1; then
  mhcflurry-downloads fetch || { echo "WARN: mhcflurry-downloads fetch failed. Try: conda activate ${ENV_NAME}; export LD_LIBRARY_PATH=\"${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH:-}\"; mhcflurry-downloads fetch"; }
else
  echo "WARN: mhcflurry-downloads not on PATH"
fi

if ! command -v vep >/dev/null 2>&1; then
  echo "NOTE: VEP not in this env. For APPM VEP annotation either:"
  echo "  - conda env create -f conda/env.neoag-vep.yml && use that vep on PATH"
  echo "  - or provide pre-computed vep_appm.tsv in run config"
fi

PREFIX="$(conda_safe env list | awk -v n="${ENV_NAME}" '$1==n {print $NF}')"
if [[ -z "${PREFIX}" || ! -d "${PREFIX}" ]]; then
  echo "ERROR: could not resolve conda prefix for ${ENV_NAME}" >&2
  exit 1
fi

cat > "${TOOLS_ENV_SH}" <<EOF
# Generated by scripts/setup_tools_env.sh — source before neoag-v03 run-full
# Usage: source conf/tools.env.sh
export NEOAG_PROJECT_ROOT="${ROOT}"
export NEOAG_TOOLS_ROOT="${ROOT}"
export NEOAG_CONDA_BASE="${CONDA_BASE}"
export NEOAG_CONDA_ENV="${ENV_NAME}"
export PATH="${PREFIX}/bin:\${PATH}"
export LD_LIBRARY_PATH="${PREFIX}/lib:\${LD_LIBRARY_PATH:-}"
export TF_USE_LEGACY_KERAS="\${TF_USE_LEGACY_KERAS:-1}"
export NEOAG_TOOLS_ROOT="${ROOT}"

# NetMHCpan (set after scripts/install_netmhcpan.sh)
export NETMHCPAN_HOME="${NETMHCPAN_HOME}"
export NEOAG_NETMHCPAN_TMPDIR="\${NEOAG_NETMHCPAN_TMPDIR:-\${NETMHCPAN_HOME}/tmp}"
if [[ -x "\${NETMHCPAN_HOME}/netMHCpan" ]]; then
  export PATH="\${NETMHCPAN_HOME}:\${PATH}"
fi

# Optional: pVACtools via Docker instead of conda (uncomment to use)
# export NEOAG_PVAC_DOCKER="griffithlab/pvactools:6.1.0"
EOF

echo "==> Wrote ${TOOLS_ENV_SH}"
echo ""
echo "Activate for this shell:"
echo "  source ${TOOLS_ENV_SH}"
echo ""
echo "Verify:"
echo "  source ${TOOLS_ENV_SH} && neoag-v03 check-tools"
echo ""
echo "NetMHCpan (manual, academic license):"
echo "  NEOAG_NETMHCPAN_HOME=${NETMHCPAN_HOME} bash scripts/install_netmhcpan.sh /path/to/netMHCpan-4.2c.Linux.tar.gz"

set +u
conda activate "${ENV_NAME}"
set -u
echo ""
echo "==> Quick check in env '${ENV_NAME}':"
for cmd in pvacseq pvacfuse mhcflurry-predict vep; do
  if command -v "$cmd" >/dev/null 2>&1; then
    echo "  OK  $cmd -> $(command -v "$cmd")"
  else
    echo "  MISS $cmd"
  fi
done
