#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

# Stage only the reviewed v04 release-boundary files. Runtime outputs, installed tools, references, and old dist archives are intentionally excluded.
git add -- \
  'CHANGELOG_V04_EVIDENCE_SAFETY_ESCAPE.md' \
  'tests/test_v041_appm_ccf_escape.py' \
  'src/neoag_v03/ccf_v2.py' \
  'src/neoag_v03/appm_v2.py' \
  'docs/V041_APPM_CCF_IMMUNE_ESCAPE.md' \
  'CHANGELOG_V041_APPM_CCF_IMMUNE_ESCAPE.md' \
  'RELEASE_REFRESH_20260615.md' \
  'RELEASE_V04_20260616.md' \
  'docs/RELEASE_BOUNDARY_V04.md' \
  'docs/V04_EVIDENCE_SAFETY_ESCAPE.md' \
  'pyproject.toml' \
  'profiles/default.toml' \
  'profiles/sv_wes_phase1_5.toml' \
  'conf/tools.env.sh' \
  'conf/easyfuse.nextflow.config' \
  'conf/run.snv_wes.example.toml' \
  'conf/run.snv_wes_fixture.toml' \
  'conf/snv_wes_demo.config' \
  'bin/neoag-nextflow' \
  'scripts/write_release_manifest.py' \
  'scripts/package_v04_release.py' \
  'docs/release_audit/V04_COMMIT_BOUNDARY_AUDIT.md' \
  'scripts/stage_v04_release_boundary.sh' \
  'src/neoag_v03/adapters/bigmhc_im.py' \
  'src/neoag_v03/adapters/deepimmuno.py' \
  'src/neoag_v03/adapters/easyfuse_adapter.py' \
  'src/neoag_v03/adapters/event_catalog.py' \
  'src/neoag_v03/adapters/facets.py' \
  'src/neoag_v03/adapters/iedb_immunogenicity.py' \
  'src/neoag_v03/adapters/lohhla.py' \
  'src/neoag_v03/adapters/mhcflurry.py' \
  'src/neoag_v03/adapters/netmhcpan.py' \
  'src/neoag_v03/adapters/netmhcstabpan.py' \
  'src/neoag_v03/adapters/peptide_input.py' \
  'src/neoag_v03/adapters/prime.py' \
  'src/neoag_v03/appm_lite.py' \
  'src/neoag_v03/ccf_lite.py' \
  'src/neoag_v03/cli.py' \
  'src/neoag_v03/config.py' \
  'src/neoag_v03/evidence_layer.py' \
  'src/neoag_v03/evidence_provenance.py' \
  'src/neoag_v03/immune_escape.py' \
  'src/neoag_v03/immune_escape_resistance.py' \
  'src/neoag_v03/immunogenicity_composite.py' \
  'src/neoag_v03/input_router.py' \
  'src/neoag_v03/model_layers.py' \
  'src/neoag_v03/peptide_safety_gate.py' \
  'src/neoag_v03/pipeline_v03.py' \
  'src/neoag_v03/preflight.py' \
  'src/neoag_v03/presentation.py' \
  'src/neoag_v03/schemas.py' \
  'src/neoag_v03/scoring_v03.py' \
  'src/neoag_v03/snv_call/__init__.py' \
  'src/neoag_v03/snv_call/mutect2.py' \
  'src/neoag_v03/snv_call/pipeline.py' \
  'src/neoag_v03/sv/phase1.py' \
  'src/neoag_v03/sv/schemas_sv.py' \
  'src/neoag_v03/sv/score_pipeline.py' \
  'src/neoag_v03/sv/wes_adapter.py' \
  'src/neoag_v03/sv/wes_capture.py' \
  'src/neoag_v03/sv/wes_filter.py' \
  'src/neoag_v03/tools/registry.py' \
  'src/neoag_v03/tools/runner.py' \
  'src/neoag_v03/vep/__init__.py' \
  'src/neoag_v03/vep/annotate.py' \
  'src/neoag_v03/vep/extract_peptides.py' \
  'data/fixtures/easyfuse_fusions.pass.tsv' \
  'data/fixtures/hla_loh_lost.tsv' \
  'data/fixtures/vep_immune_escape.tsv' \
  'data/fixtures_snv/hla.txt' \
  'data/fixtures_snv/mini_ref.dict' \
  'data/fixtures_snv/mini_ref.fa' \
  'data/fixtures_snv/mini_ref.fa.fai' \
  'data/fixtures_snv/mini_somatic.vcf' \
  'data/fixtures_snv/wes_capture.bed' \
  'tests/conftest.py' \
  'tests/test_appm_escape_consistency.py' \
  'tests/test_easyfuse_adapter.py' \
  'tests/test_evidence_provenance.py' \
  'tests/test_immune_escape_resistance.py' \
  'tests/test_intermediates.py' \
  'tests/test_peptide_input.py' \
  'tests/test_preflight.py' \
  'tests/test_snv_phase1_wes.py' \
  'tests/test_tools.py' \
  'tests/test_v03.py' \
  'tests/test_v04_evidence_safety_escape.py' \
  'modules/gatk_filter_mutect_calls/main.nf' \
  'modules/gatk_mutect2/main.nf' \
  'modules/snv_write_run_config/main.nf' \
  'workflows/snv_phase1_wes.nf' \
  'workflows/snv_phase1_wes_fixture.nf'

git status --short --untracked-files=no
