process SNV_WRITE_RUN_CONFIG {
    tag "${sample_id}"
    publishDir "${params.outdir}", mode: 'copy', pattern: 'run.snv_wes.generated.toml'

    input:
    val sample_id
    val profile_name
    path filtered_vcf
    val hla_alleles
    val tumor_sample_name
    val normal_sample_name
    val upstream_stub

    output:
    path "run.snv_wes.generated.toml", emit: run_config

    script:
    def stub = upstream_stub ? 'true' : 'false'
    def hla = hla_alleles.join('","')
    """
    cat > run.snv_wes.generated.toml <<EOF
# Generated by Nextflow SNV Phase 1 WES

[sample]
id = "${sample_id}"
profile = "${profile_name}"

[tools]
stub = ${stub}
enabled = ["pvacseq", "netmhcpan", "mhcflurry", "vep"]

[inputs]
hla_alleles = ["${hla}"]
tumor_vcf = "${filtered_vcf}"
tumor_sample_name = "${tumor_sample_name}"
normal_sample_name = "${normal_sample_name}"
variants_vcf = "${filtered_vcf}"
extract_appm_from_vcf = true
expression = "${params.expression_tsv ?: projectDir + '/../data/fixtures/gene_expression.tsv'}"
cnv = "${params.cnv_tsv ?: projectDir + '/../data/fixtures/cnv_segments.tsv'}"
normal_expression = "${params.normal_expression ?: projectDir + '/../resources/normal_expression.example.tsv'}"
normal_hla_ligands = "${params.normal_hla_ligands ?: projectDir + '/../resources/normal_hla_ligands.example.tsv'}"
EOF
    """
}
