from __future__ import annotations

INTENT_TO_SKILLS: dict[str, list[str]] = {
    "input_check": ["neoag-input-qc"],
    "tool_check": ["neoag-tool-and-reference-qc"],
    "demo_smoke": ["neoag-run-demo-and-smoke"],
    "sliding_run": ["neoag-input-qc", "neoag-sliding-run"],
    "run_scoring": ["neoag-input-qc", "neoag-evidence-scoring"],
    "fusion_rna_run": ["neoag-fusion-rna-run"],
    "rna_fastq_to_tpm": ["neoag-rna-fastq-to-tpm"],
    "appm_escape_review": ["neoag-input-qc", "neoag-hla-loh-appm-review"],
    "hla_typing_compare": ["neoag-hla-typing-run-and-compare"],
    "ccf_review": ["neoag-input-qc", "neoag-ccf-clonality-review"],
    "purity_cnv_review": ["neoag-purity-cnv-run-and-review"],
    "ranking_compare": ["neoag-input-qc", "neoag-ranking-compare"],
    "patient_report_update": ["neoag-input-qc", "neoag-ranking-compare", "neoag-hla-loh-appm-review", "neoag-ccf-clonality-review", "neoag-patient-report"],
    "experiment_design": ["neoag-input-qc", "neoag-ranking-compare", "neoag-hla-loh-appm-review", "neoag-ccf-clonality-review"],
    "general_explanation": [],
    "project_overview": [],
    "check_status": [],
    "inspect_results": ["neoag-result-inspector"],
    "data_transfer": [],
    "debug_error": [],
    "update_docs": [],
    "git_release": [],
    "setup_tool": ["neoag-tool-and-reference-qc"],
    "workflow_run_request": ["neoag-input-qc"],
}

INTENT_DESCRIPTIONS = {
    "input_check": "Inspect provided sample files/result directory and recommend the appropriate Project B workflow.",
    "tool_check": "Check external tool and reference readiness.",
    "demo_smoke": "Run or plan Project B pytest/run-demo/Nextflow smoke tests.",
    "sliding_run": "Plan the staged or one-command sliding-window SNV/InDel neoantigen workflow from a somatic VCF.",
    "run_scoring": "Plan or run evidence scoring from raw_events/raw_peptides/presentation inputs.",
    "fusion_rna_run": "Run or review RNA fusion workflows across EasyFuse, STAR-Fusion, Arriba, and FusionCatcher.",
    "rna_fastq_to_tpm": "Prepare or review RNA expression TPM evidence from RNA FASTQ, BAM, or existing expression files.",
    "appm_escape_review": "Review APPM, HLA LOH, and immune escape evidence.",
    "hla_typing_compare": "Compare or plan HLA typing across OptiType, SpecHLA, and HLA-LA.",
    "ccf_review": "Review CCF, purity, clonality, and CCF modifiers.",
    "purity_cnv_review": "Review or plan purity/CNV analysis across FACETS, PURPLE, Sequenza, and ASCAT.",
    "ranking_compare": "Compare NetMHCpan42 ranking with recommendation ranking.",
    "patient_report_update": "Generate or update the patient-facing report.",
    "experiment_design": "Create an experimental validation candidate grouping plan.",
    "general_explanation": "Explain concepts without executing workflows.",
    "project_overview": "Summarize this project and its capabilities without executing workflows.",
    "check_status": "Check status of existing jobs, logs, and outputs.",
    "inspect_results": "Interpret existing result files or reports.",
    "data_transfer": "Plan or validate data copy/synchronization commands.",
    "debug_error": "Diagnose an error log or failed command.",
    "update_docs": "Update project documentation.",
    "git_release": "Prepare commits, release branches, or push instructions.",
    "setup_tool": "Install or configure external tools and references.",
    "workflow_run_request": "Run a registered or external bioinformatics workflow.",
}
